overrides: coala.yaml

name: coala-json
description: A collection of coala json utilities
url: https://gitlab.com/coala/coala-json
license: MIT
build_version: 0.1.0
current_version: 0.1.0
version: 0.1.0
package_module: coala_json
docs_dir: false
test_file_glob: 'test_*.py *Test.py'
entry_points:
  console_scripts:
    - coala-json=coala_json.reporters.cli.cli:main

configuration:
  template_dir:
    - .moban.dt/
    - ../coala-mobans/templates/
    - ../coala-mobans/assets/
  configuration: .moban.yaml
  configuration_dir: ../coala-mobans/
targets:
  - .gitignore: coala-gitignore.jj2
  - setup.py: coala-setup.py.jj2
  - setup.cfg: setup.cfg.jj2
#  - gitlab-ci.yml: ci/gitlab-ci.yml.jj2
  - test-requirements.txt: core-test-requirements.txt.jj2
  - .ci/check_moban.sh: ci/check_moban.sh
  - .ci/run_with_env.cmd: run_with_env.cmd
  - tests/conftest.py: conftest.py
