overrides: coala.yaml

name: coala-json
description: A collection of coala json utilities
url: https://gitlab.com/coala/coala-json
license: MIT
version: 0.0.1-dev
package_module: coala_json
docs_dir: false
test_file_glob: 'test_*.py'

configuration:
  template_dir:
    - ../coala-mobans/templates/
    - ../coala-mobans/assets/
  configuration: .moban.yaml
  configuration_dir: ../coala-mobans/
targets:
  - .gitignore: coala-gitignore.jj2
  - .gitlab-ci.yml: ci/gitlab-ci.yml.jj2
  - setup.py: coala-setup.py.jj2
  - setup.cfg: setup.cfg.jj2
  - test-requirements.txt: test-requirements.txt.jj2
  - .ci/check_moban.sh: ci/check_moban.sh
  - .ci/appveyor.yml: ci/appveyor.yml.jj2
  - .ci/run_with_env.cmd: run_with_env.cmd
  - tests/conftest.py: conftest.py
