environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\.ci\\run_with_env.cmd"
    PIP_CACHE_DIR: C:\pip_cache

  matrix:
    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.4"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.4"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"

cache:
  - "C:\\pip_cache"
  - "C:\\Users\\appveyor\\AppData\\Local\\coala-bears\\coala-bears"

install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "%CMD_IN_ENV% python -m pip install --upgrade setuptools==21 pip~=9.0.1"
  - "%CMD_IN_ENV% python -m pip install -r test-requirements.txt"

  # Add to path the current folder
  - "SET PYTHONPATH=%PYTHONPATH%;%CD%"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - python -m pip --version
  - python -c "import setuptools; print(setuptools.__version__)"

  - py.test

  - if not %PYTHON_VERSION% == 2.7
      python -m pip install
      git+https://github.com/coala/coala#egg=coala
      git+https://github.com/coala/coala-bears#egg=coala-bears
      coala-json


  - if not %PYTHON_VERSION% == 2.7
      coala --json -o output.json

on_success:
  - codecov

on_failure:
  - codecov

matrix:
  fast_finish: true

on_finish:
  - if not %PYTHON_VERSION% == 2.7
    coala-json --junit -f output.json -o report.xml
  - if not %PYTHON_VERSION% == 2.7
    "%CMD_IN_ENV% python httpreq.py
