environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\.ci\\run_with_env.cmd"
    PIP_CACHE_DIR: C:\pip_cache

  matrix:
    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.4"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.4"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"

cache:
  - "C:\\pip_cache"
  - "C:\\Users\\appveyor\\AppData\\Local\\coala-bears\\coala-bears"

install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "%CMD_IN_ENV% python -m pip install --upgrade setuptools==21 pip~=9.0.1"
  - "%CMD_IN_ENV% python -m pip install -r test-requirements.txt"
  - "%CMD_IN_ENV% pip install coala-json"

  # Add to path the current folder
  - "SET PYTHONPATH=%PYTHONPATH%;%CD%"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "%CMD_IN_ENV% coala --json -o output.json"
  - "%CMD_IN_ENV% python -m pytest"

on_finish:
  - if not %PYTHON_VERSION% == 2.7
    coala-json --junit -f output.json -o report.xml
  - if not %PYTHON_VERSION% == 2.7
    "%CMD_IN_ENV% python C:\\projects\\coala-json\\coala_json\\reporters\\cli\\cli.py --appveyor -f $APPVEYOR_JOB_ID"
