[build]
  publish = "docs/_build/html"
  command = "virtualenv -p python3 coala-venv && source coala-venv/bin/activate && cd docs && pip install -r requirements.txt && export PYTHONPATH=$(pwd) && make html"
